#!/bin/bash

wget https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-1.5.2-linux-x86_64.tar.gz
tar -xvzf julia-1.5.2-linux-x86_64.tar.gz
cp -r julia-1.5.2 /opt/
ln -s /opt/julia-1.5.2/bin/julia /usr/local/bin/julia